// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPdBjxHu26G-h7q-c1ri-cDcm3AjFCM-k',
    appId: '1:431489202827:web:12679e0f8f7d015d51b28e',
    messagingSenderId: '431489202827',
    projectId: 'stanchat-44420',
    authDomain: 'stanchat-44420.firebaseapp.com',
    storageBucket: 'stanchat-44420.firebasestorage.app',
    measurementId: 'G-C89Y4EEP7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdENELaGU_2HEYUKisAG9qKyeC1wQWuMo',
    appId: '1:431489202827:android:d7bef552b98af7ec51b28e',
    messagingSenderId: '431489202827',
    projectId: 'stanchat-44420',
    storageBucket: 'stanchat-44420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-mU4xAx51xKZkYMj_o-J8-UFfGgF5xo',
    appId: '1:431489202827:ios:af23af30c32efd1b51b28e',
    messagingSenderId: '431489202827',
    projectId: 'stanchat-44420',
    storageBucket: 'stanchat-44420.firebasestorage.app',
    iosBundleId: 'com.example.stanchatMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-mU4xAx51xKZkYMj_o-J8-UFfGgF5xo',
    appId: '1:431489202827:ios:af23af30c32efd1b51b28e',
    messagingSenderId: '431489202827',
    projectId: 'stanchat-44420',
    storageBucket: 'stanchat-44420.firebasestorage.app',
    iosBundleId: 'com.example.stanchatMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPdBjxHu26G-h7q-c1ri-cDcm3AjFCM-k',
    appId: '1:431489202827:web:95c09b7720ea494051b28e',
    messagingSenderId: '431489202827',
    projectId: 'stanchat-44420',
    authDomain: 'stanchat-44420.firebaseapp.com',
    storageBucket: 'stanchat-44420.firebasestorage.app',
    measurementId: 'G-W1CWE9Y89R',
  );
}
